const genres = [
  { value: "DEFAULT", label: "Select Genres", disabled: true },
  { value: "Action", label: "Action" },
  { value: "RPG", label: "RPG" },
  { value: "Adventure", label: "Adventure" },
  { value: "Indie", label: "Indie" },
  { value: "Strategy", label: "Strategy" },
  { value: "Shooter", label: "Shooter" },
  { value: "Casual", label: "Casual" },
  { value: "Simulation", label: "Simulation" },
  { value: "Puzzle", label: "Puzzle" },
  { value: "Arcade", label: "Arcade" },
  { value: "Platformer", label: "Platformer" },
  { value: "Racing", label: "Racing" },
  { value: "Multiplayer", label: "Massively Multiplayer" },
  { value: "Sports", label: "Sports" },
  { value: "Fighting", label: "Fighting" },
  { value: "Family", label: "Family" },
  { value: "Board", label: "Board Games" },
  { value: "Educational", label: "Educational" },
  { value: "Card", label: "Card" },
];
export default genres;
